portifolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path("", include('projects.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from projects import views
app_name = "projects"
urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    #path('addproject', views.add_project),
    path('<str:title>', views.project_detail, name="project_detail"),
]

projects/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.ImageField(upload_to="media/projects")

projects/forms.py
from django.forms import ModelForm
from projects.models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'technology', 'image']

projects/views.py
from django.shortcuts import render
#from django.http import HttpResponseRedirect
from projects.models import Project
#from .forms import ProjectForm
#from django.contrib.auth.decorators import login_required
# Create your views here.

def all_projects(request):
    projects = Project.objects.all()
    return render(request, 'projects/all_projects.html', {'projects': projects})


def project_detail(request, title):
    project = Project.objects.get(title=title)
    return render(request, 'projects/single_project.html', {'project': project})

#@login_required
#def add_project(request):
#    if request.method == "POST":
#        form = ProjectForm(request.POST, request.FILES)
#        if form.is_valid():
#            form.save()
#            return HttpResponseRedirect("../projects")
#    else:
#        form = ProjectForm()
#    return render(request, 'projects/add_project.html', {'form': form})

projects/templates/projects/add_project.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Projects</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/5f81a82863.js" crossorigin="anonymous"></script>

</head>

<body>
  <div class="row">

    <nav class="col-md-2 d-none d-md-block bg-dark sidebar">
      <div class="sidebar-sticky">
        <br style = "line-height:1;">
        <a class="nav-link" href="."><i class="fas fa-home"></i> Home</a>

      </div>
    </nav>
    <main class="col-md-9 ml-sm-auto col-lg-10 px-4" role=main>
      <div class="container">
      <br style = "line-height:1;">

      <h3>Add a project</h3>
      <br style = "line-height:4;">
      <form action="addproject" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Submit" />
      </form>
    </div>
    </main>

  </div>
  </div>
</body>

</html>

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content %}
  <p>
  <div class="card-columns">
    {% for project in projects %}

    <div class="col">
      <div class="card border-secondary" >
        <a class="card-link" href={% url 'projects:project_detail' project.title %}>
        <img class="card-img-top" src="{{ project.image.url }}" style="transform: rotate(0);"/>
        </a> 
        <div class="card-body bg-dark text-light rounded-bottom" style="position: relative;">
          <h5 class="card-title">{{ project.title }}</h5>
          <p class="card-text">{{ project.description }}</p>
          <a href={% url 'projects:project_detail' project.title %} class="btn btn-primary">
           Read More
          </a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

{% endblock %}

projects/templates/projects/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>{% block title %} Portifolio {% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/5f81a82863.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static "admin/css/theme.css" %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

  <style>
    html,
    body {
      height: 100%;
    }

    .flex-fill {
      flex: 1;
    }
  </style>
</head>

<body>
  <main class="d-md-flex flex-column h-100">
    <div class="container-fluid d-flex h-100">
      <div class="row flex-fill bg-primary text-light">
        <nav class="col-2 d-none d-md-block bg-light sidebar bg-dark d-flex flex-column flex-fill">
          <div class="sidebar-sticky text-center">
            {% block sidebar %}
            <p>
              <h1 class="d-none d-lg-block" style="font-family: Oswald;"> Portifolio </h1>
              <p></p>
              <a class="nav-link text-light p-0" href="."><span class="d-none d-lg-block"><i class="fas fa-home"></i>
                  Home</span><span class="d-lg-none"><i class="fas fa-home"></i></span></a>
            {% endblock  %}
          </div>
        </nav>

        <div class="col-10 ml-sm-auto px-4 bg-primary text-break">

          {% block content %}
          {% endblock %}
          <!--<footer class="pt-5 my-5 border-top">
            <div class="row flex-fill">
              <div class="col">"Footer"</div>
              <div class="col">"Footer"</div>
              <div class="col">"Footer"</div>

            </div>

          </footer>-->
        </div>
      </div>

    </div>
</body>
</main>

</html>

projects/templates/projects/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-*">
  <title>Title</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>

  
</body>

</html>

projects/templates/projects/single_project.html
{% extends 'projects/base.html' %}
{% load static %}

{% block title %} {{project.title}} {% endblock title %}

{% block content %}
<div class="row flex-fill d-flex">
  <div class="media">
    <img class="img-fluid rounded float-left border border-0 mr-4" style="max-width: 40%;"
      src="{{ project.image.url }}">
    <div class="media-body text-light">
      <h4 class="mt-0"> {{project.title}} </h4>
      <p class="mb-0 font-weight-bold">Description:</p>
      <p class="mb-3">{{project.description}}</p>
      <p class="mb-0 font-weight-bold">Technology:</p>
      <p class="mb-3">{{project.technology}}</p>

    </div>
  </div>
</div>
{% endblock %}